name: Update Script from Pastebin

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch content from Pastebin
        run: |
          curl -o chess https://pastebin.com/raw/wUWxu4BW

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "github-actions"
          git add chess
          git commit -m "Auto update script from Pastebin" || echo "No changes to commit"
          git push
